/**
 * Scalable exercise database. Structure supports 1,000+ entries — this seed
 * ships ~40 exercises covering the main movement patterns. New entries can be
 * added without changing consumers.
 *
 * Sources for programming defaults: ACSM 11th ed., NSCA Essentials 4th ed.,
 * NASM 7th ed., WHO 2020 activity guidelines, McGill (spine), Haff/Triplett.
 */

export type Category =
  | "push"
  | "pull"
  | "legs"
  | "core"
  | "cardio"
  | "mobility"
  | "warmup"
  | "cooldown";

export type Equipment =
  | "none"
  | "dumbbells"
  | "barbell"
  | "kettlebell"
  | "resistance-band"
  | "pullup-bar"
  | "bench"
  | "mat";

export type Level = "beginner" | "intermediate" | "advanced";

export type Goal =
  | "fat-loss"
  | "muscle-gain"
  | "strength"
  | "endurance"
  | "mobility"
  | "general-fitness";

export type Muscle =
  | "chest"
  | "back"
  | "shoulders"
  | "biceps"
  | "triceps"
  | "quads"
  | "hamstrings"
  | "glutes"
  | "calves"
  | "core"
  | "full-body";

export type Injury =
  | "knee"
  | "lower-back"
  | "shoulder"
  | "wrist"
  | "ankle"
  | "neck"
  | "hip";

export type Location = "home" | "gym" | "outdoor";

export type Pose =
  | "push-up"
  | "squat"
  | "plank"
  | "burpee"
  | "warmup"
  | "cooldown"
  | "default";

export interface Exercise {
  id: string;
  name: string;
  latin: string;
  category: Category;
  level: Level;
  equipment: Equipment[];
  primary: Muscle[];
  secondary: Muscle[];
  location: Location[];
  goals: Goal[];
  /** joints/regions to avoid this movement for */
  contraindicated: Injury[];
  pose: Pose;
  /** seconds per full rep cycle */
  tempo: number;
  /** kcal per minute, moderate effort (~70 kg adult) */
  caloriesPerMin: number;
  recommendedSets: number;
  recommendedReps: string;
  restSeconds: number;
  cue: string;
  mistakes: string[];
  safety: string[];
  breathing: string;
  /** ordered ladder: easier → harder (id list including this exercise) */
  progression: string[];
  alternatives: string[];
  reference: string;
}

const REF_ACSM = "ACSM Guidelines for Exercise Testing & Prescription, 11th ed.";
const REF_NSCA = "NSCA Essentials of Strength Training & Conditioning, 4th ed.";
const REF_NASM = "NASM Essentials of Personal Fitness Training, 7th ed.";
const REF_MCGILL = "McGill S. — Ultimate Back Fitness & Performance, 5th ed.";
const REF_WHO = "WHO Guidelines on Physical Activity, 2020.";

export const EXERCISES: Exercise[] = [
  // ============ PUSH — chest/shoulders/triceps ============
  {
    id: "wall-pushup",
    name: "ضغط على الحائط",
    latin: "Wall Push-Up",
    category: "push",
    level: "beginner",
    equipment: ["none"],
    primary: ["chest"],
    secondary: ["triceps", "shoulders", "core"],
    location: ["home", "outdoor"],
    goals: ["general-fitness", "endurance"],
    contraindicated: [],
    pose: "push-up",
    tempo: 3,
    caloriesPerMin: 4,
    recommendedSets: 3,
    recommendedReps: "12-15",
    restSeconds: 45,
    cue: "الجسم بخط مستقيم، المرفقان بزاوية 45°، ادفع بقوة",
    mistakes: ["ترخي الوسط", "المرفقان مفتوحان تماماً", "الرأس متدلٍّ"],
    safety: ["أوقف إن شعرت بألم في الكتف أو الرسغ"],
    breathing: "شهيق نزولاً · زفير دفعاً",
    progression: ["wall-pushup", "incline-pushup", "pushup", "diamond-pushup", "archer-pushup", "one-arm-pushup"],
    alternatives: ["incline-pushup"],
    reference: REF_NASM,
  },
  {
    id: "incline-pushup",
    name: "ضغط مائل",
    latin: "Incline Push-Up",
    category: "push",
    level: "beginner",
    equipment: ["bench"],
    primary: ["chest"],
    secondary: ["triceps", "shoulders", "core"],
    location: ["home", "gym"],
    goals: ["muscle-gain", "general-fitness"],
    contraindicated: ["wrist"],
    pose: "push-up",
    tempo: 3,
    caloriesPerMin: 5,
    recommendedSets: 3,
    recommendedReps: "10-12",
    restSeconds: 60,
    cue: "اليدان أوسع من الكتفين قليلاً، الجذع مشدود",
    mistakes: ["الوركان مرتفعان", "المرفق يتجاوز الرسغ"],
    safety: ["استخدم سطحاً ثابتاً لا يتحرك"],
    breathing: "شهيق نزولاً · زفير دفعاً",
    progression: ["wall-pushup", "incline-pushup", "pushup", "diamond-pushup", "archer-pushup", "one-arm-pushup"],
    alternatives: ["wall-pushup", "knee-pushup"],
    reference: REF_ACSM,
  },
  {
    id: "knee-pushup",
    name: "ضغط بالركبتين",
    latin: "Knee Push-Up",
    category: "push",
    level: "beginner",
    equipment: ["mat"],
    primary: ["chest"],
    secondary: ["triceps", "core"],
    location: ["home"],
    goals: ["general-fitness"],
    contraindicated: ["wrist"],
    pose: "push-up",
    tempo: 3,
    caloriesPerMin: 5,
    recommendedSets: 3,
    recommendedReps: "10-12",
    restSeconds: 60,
    cue: "الركبتان على الأرض، الحوض مشدود، الجذع بخط مستقيم من الرأس للركبة",
    mistakes: ["تدلي الحوض", "الرأس للأسفل"],
    safety: ["ضع وسادة تحت الركبتين"],
    breathing: "شهيق نزولاً · زفير دفعاً",
    progression: ["knee-pushup", "pushup", "diamond-pushup"],
    alternatives: ["incline-pushup"],
    reference: REF_NASM,
  },
  {
    id: "pushup",
    name: "تمرين الضغط",
    latin: "Standard Push-Up",
    category: "push",
    level: "intermediate",
    equipment: ["mat"],
    primary: ["chest"],
    secondary: ["triceps", "shoulders", "core"],
    location: ["home", "gym", "outdoor"],
    goals: ["muscle-gain", "strength", "general-fitness"],
    contraindicated: ["wrist", "shoulder"],
    pose: "push-up",
    tempo: 3,
    caloriesPerMin: 8,
    recommendedSets: 4,
    recommendedReps: "10-15",
    restSeconds: 60,
    cue: "المرفقان بزاوية 45°، نزول متحكم لمدة 3 ثواني",
    mistakes: ["فتح المرفقين 90°", "تدلي الحوض", "الرأس متقدم"],
    safety: ["توقف عند وخز في الكتف"],
    breathing: "شهيق نزولاً · زفير دفعاً",
    progression: ["wall-pushup", "incline-pushup", "pushup", "diamond-pushup", "archer-pushup", "one-arm-pushup"],
    alternatives: ["knee-pushup", "incline-pushup"],
    reference: REF_ACSM,
  },
  {
    id: "diamond-pushup",
    name: "ضغط الماسة",
    latin: "Diamond Push-Up",
    category: "push",
    level: "advanced",
    equipment: ["mat"],
    primary: ["triceps"],
    secondary: ["chest", "shoulders"],
    location: ["home", "gym"],
    goals: ["strength", "muscle-gain"],
    contraindicated: ["wrist", "shoulder"],
    pose: "push-up",
    tempo: 3,
    caloriesPerMin: 9,
    recommendedSets: 4,
    recommendedReps: "8-12",
    restSeconds: 75,
    cue: "الإبهامان والسبابتان تشكلان ماسة تحت الصدر",
    mistakes: ["فرد المرفقين", "نزول سريع دون تحكم"],
    safety: ["توقف عند ألم في الرسغ"],
    breathing: "شهيق نزولاً · زفير دفعاً",
    progression: ["pushup", "diamond-pushup", "archer-pushup", "one-arm-pushup"],
    alternatives: ["pushup"],
    reference: REF_NSCA,
  },
  {
    id: "archer-pushup",
    name: "ضغط الرامي",
    latin: "Archer Push-Up",
    category: "push",
    level: "advanced",
    equipment: ["mat"],
    primary: ["chest"],
    secondary: ["triceps", "core"],
    location: ["home", "gym"],
    goals: ["strength", "muscle-gain"],
    contraindicated: ["shoulder", "wrist"],
    pose: "push-up",
    tempo: 4,
    caloriesPerMin: 10,
    recommendedSets: 4,
    recommendedReps: "5-8 لكل جهة",
    restSeconds: 90,
    cue: "انزل نحو ذراع واحدة والأخرى ممتدة كوتر القوس",
    mistakes: ["الوسط ملتوٍ", "الحوض ينخفض"],
    safety: ["زد المدى تدريجياً"],
    breathing: "شهيق نزولاً · زفير دفعاً",
    progression: ["diamond-pushup", "archer-pushup", "one-arm-pushup"],
    alternatives: ["diamond-pushup"],
    reference: REF_NSCA,
  },
  {
    id: "one-arm-pushup",
    name: "ضغط بذراع واحدة",
    latin: "One-Arm Push-Up",
    category: "push",
    level: "advanced",
    equipment: ["mat"],
    primary: ["chest"],
    secondary: ["core", "triceps"],
    location: ["home", "gym"],
    goals: ["strength"],
    contraindicated: ["shoulder", "wrist", "lower-back"],
    pose: "push-up",
    tempo: 5,
    caloriesPerMin: 12,
    recommendedSets: 5,
    recommendedReps: "3-5 لكل جهة",
    restSeconds: 120,
    cue: "القدمان متباعدتان جداً للاتزان، الجذع مشدود بالكامل",
    mistakes: ["الالتفاف بالكتف", "الوسط يهبط"],
    safety: ["اتقن Archer قبل المحاولة"],
    breathing: "شهيق نزولاً · زفير دفعاً",
    progression: ["archer-pushup", "one-arm-pushup"],
    alternatives: ["archer-pushup"],
    reference: REF_NSCA,
  },

  // ============ PULL ============
  {
    id: "band-row",
    name: "تجديف بشريط المقاومة",
    latin: "Resistance Band Row",
    category: "pull",
    level: "beginner",
    equipment: ["resistance-band"],
    primary: ["back"],
    secondary: ["biceps"],
    location: ["home", "outdoor"],
    goals: ["muscle-gain", "general-fitness"],
    contraindicated: [],
    pose: "default",
    tempo: 3,
    caloriesPerMin: 6,
    recommendedSets: 3,
    recommendedReps: "12-15",
    restSeconds: 60,
    cue: "اسحب المرفقين للخلف واضغط لوحي الكتف",
    mistakes: ["رفع الكتفين", "التأرجح بالجذع"],
    safety: ["ثبّت الشريط على مثبت آمن"],
    breathing: "زفير سحباً · شهيق عودةً",
    progression: ["band-row", "australian-pullup", "negative-pullup", "pullup", "weighted-pullup"],
    alternatives: ["dumbbell-row"],
    reference: REF_NASM,
  },
  {
    id: "australian-pullup",
    name: "تجديف أسترالي",
    latin: "Australian Pull-Up (Inverted Row)",
    category: "pull",
    level: "intermediate",
    equipment: ["pullup-bar"],
    primary: ["back"],
    secondary: ["biceps", "core"],
    location: ["home", "gym", "outdoor"],
    goals: ["muscle-gain", "strength"],
    contraindicated: ["shoulder"],
    pose: "default",
    tempo: 3,
    caloriesPerMin: 8,
    recommendedSets: 4,
    recommendedReps: "8-12",
    restSeconds: 75,
    cue: "الجسم بخط مستقيم، اسحب الصدر نحو البار",
    mistakes: ["الحوض يهبط", "المرفقان مفتوحان"],
    safety: ["احرص على ثبات البار"],
    breathing: "زفير سحباً · شهيق نزولاً",
    progression: ["band-row", "australian-pullup", "negative-pullup", "pullup", "weighted-pullup"],
    alternatives: ["band-row"],
    reference: REF_NSCA,
  },
  {
    id: "negative-pullup",
    name: "سحب سلبي",
    latin: "Negative Pull-Up",
    category: "pull",
    level: "intermediate",
    equipment: ["pullup-bar"],
    primary: ["back"],
    secondary: ["biceps"],
    location: ["home", "gym"],
    goals: ["strength"],
    contraindicated: ["shoulder", "wrist"],
    pose: "default",
    tempo: 5,
    caloriesPerMin: 9,
    recommendedSets: 4,
    recommendedReps: "4-6",
    restSeconds: 90,
    cue: "ابدأ من الأعلى وانزل ببطء 4-5 ثوانٍ",
    mistakes: ["نزول سريع", "استخدام الزخم"],
    safety: ["استخدم مقعداً للصعود"],
    breathing: "شهيق نزولاً بتحكم",
    progression: ["australian-pullup", "negative-pullup", "pullup", "weighted-pullup"],
    alternatives: ["band-row"],
    reference: REF_NSCA,
  },
  {
    id: "pullup",
    name: "شد على البار",
    latin: "Standard Pull-Up",
    category: "pull",
    level: "advanced",
    equipment: ["pullup-bar"],
    primary: ["back"],
    secondary: ["biceps", "core"],
    location: ["home", "gym", "outdoor"],
    goals: ["strength", "muscle-gain"],
    contraindicated: ["shoulder"],
    pose: "default",
    tempo: 3,
    caloriesPerMin: 10,
    recommendedSets: 5,
    recommendedReps: "5-10",
    restSeconds: 120,
    cue: "قبضة أوسع من الكتفين، اسحب حتى تجاوز الذقن للبار",
    mistakes: ["التأرجح (kipping غير مقصود)", "عدم كمال المدى"],
    safety: ["توقف عند فرقعة في الكتف"],
    breathing: "زفير صعوداً · شهيق نزولاً",
    progression: ["negative-pullup", "pullup", "weighted-pullup"],
    alternatives: ["negative-pullup", "australian-pullup"],
    reference: REF_NSCA,
  },
  {
    id: "weighted-pullup",
    name: "شد بأوزان",
    latin: "Weighted Pull-Up",
    category: "pull",
    level: "advanced",
    equipment: ["pullup-bar"],
    primary: ["back"],
    secondary: ["biceps"],
    location: ["gym"],
    goals: ["strength"],
    contraindicated: ["shoulder", "lower-back"],
    pose: "default",
    tempo: 3,
    caloriesPerMin: 12,
    recommendedSets: 4,
    recommendedReps: "3-6",
    restSeconds: 150,
    cue: "استخدم حزام أوزان، حافظ على تحكم المدى الكامل",
    mistakes: ["تجاهل المدى الكامل", "حبس النفس المطوّل"],
    safety: ["ابدأ بوزن خفيف"],
    breathing: "زفير صعوداً",
    progression: ["pullup", "weighted-pullup"],
    alternatives: ["pullup"],
    reference: REF_NSCA,
  },
  {
    id: "dumbbell-row",
    name: "تجديف بالدمبل",
    latin: "One-Arm Dumbbell Row",
    category: "pull",
    level: "intermediate",
    equipment: ["dumbbells", "bench"],
    primary: ["back"],
    secondary: ["biceps"],
    location: ["home", "gym"],
    goals: ["muscle-gain", "strength"],
    contraindicated: ["lower-back"],
    pose: "default",
    tempo: 3,
    caloriesPerMin: 7,
    recommendedSets: 4,
    recommendedReps: "10-12",
    restSeconds: 60,
    cue: "الظهر مستوٍ، اسحب الدمبل نحو الورك",
    mistakes: ["الالتواء بالكتف", "تقوّس أسفل الظهر"],
    safety: ["ثبّت اليد الأخرى على المقعد"],
    breathing: "زفير سحباً",
    progression: ["band-row", "dumbbell-row"],
    alternatives: ["band-row"],
    reference: REF_NSCA,
  },

  // ============ LEGS ============
  {
    id: "bodyweight-squat",
    name: "قرفصاء هوائية",
    latin: "Bodyweight Squat",
    category: "legs",
    level: "beginner",
    equipment: ["none"],
    primary: ["quads", "glutes"],
    secondary: ["core", "hamstrings"],
    location: ["home", "outdoor"],
    goals: ["general-fitness", "endurance", "mobility"],
    contraindicated: [],
    pose: "squat",
    tempo: 2.5,
    caloriesPerMin: 7,
    recommendedSets: 3,
    recommendedReps: "12-20",
    restSeconds: 45,
    cue: "الكعبان على الأرض، الركبتان بمحاذاة الأصابع، الصدر مرفوع",
    mistakes: ["ميل الركبتين للداخل", "رفع الكعبين", "انحناء الظهر"],
    safety: ["توقف عند ألم في الركبة"],
    breathing: "شهيق نزولاً · زفير صعوداً",
    progression: ["bodyweight-squat", "goblet-squat", "jump-squat", "pistol-squat"],
    alternatives: ["wall-sit"],
    reference: REF_NSCA,
  },
  {
    id: "goblet-squat",
    name: "قرفصاء الكأس",
    latin: "Goblet Squat",
    category: "legs",
    level: "intermediate",
    equipment: ["dumbbells", "kettlebell"],
    primary: ["quads", "glutes"],
    secondary: ["core"],
    location: ["home", "gym"],
    goals: ["strength", "muscle-gain"],
    contraindicated: ["knee"],
    pose: "squat",
    tempo: 3,
    caloriesPerMin: 8,
    recommendedSets: 4,
    recommendedReps: "10-12",
    restSeconds: 75,
    cue: "احمل الوزن قرب الصدر، مرفقاك يمرّان بين الركبتين",
    mistakes: ["تدلي الوزن", "تقوس الظهر العلوي"],
    safety: ["استخدم وزناً مناسباً"],
    breathing: "شهيق نزولاً · زفير صعوداً",
    progression: ["bodyweight-squat", "goblet-squat", "front-squat"],
    alternatives: ["bodyweight-squat"],
    reference: REF_NSCA,
  },
  {
    id: "jump-squat",
    name: "قفزة عمودية",
    latin: "Jump Squat",
    category: "legs",
    level: "intermediate",
    equipment: ["none"],
    primary: ["quads", "glutes"],
    secondary: ["calves", "core"],
    location: ["home", "outdoor"],
    goals: ["fat-loss", "endurance"],
    contraindicated: ["knee", "ankle"],
    pose: "burpee",
    tempo: 2,
    caloriesPerMin: 12,
    recommendedSets: 3,
    recommendedReps: "8-12",
    restSeconds: 60,
    cue: "هبوط ناعم من الأمشاط للكعب، امتصاص الصدمة بثني الركبتين والوركين",
    mistakes: ["هبوط بركبتين مفرودتين", "هبوط للداخل"],
    safety: ["توقف عند ألم بالركبة أو الكاحل"],
    breathing: "زفير قفزاً",
    progression: ["bodyweight-squat", "jump-squat", "box-jump"],
    alternatives: ["bodyweight-squat"],
    reference: "NSCA Plyometric Position Statement (Haff & Triplett, 2016).",
  },
  {
    id: "pistol-squat",
    name: "قرفصاء المسدس",
    latin: "Pistol Squat",
    category: "legs",
    level: "advanced",
    equipment: ["none"],
    primary: ["quads", "glutes"],
    secondary: ["core", "hamstrings"],
    location: ["home", "gym"],
    goals: ["strength", "mobility"],
    contraindicated: ["knee", "hip"],
    pose: "squat",
    tempo: 4,
    caloriesPerMin: 10,
    recommendedSets: 4,
    recommendedReps: "3-6 لكل ساق",
    restSeconds: 90,
    cue: "الساق الحرة ممتدة أماماً، انزل ببطء تام",
    mistakes: ["فقدان التوازن", "دوران الركبة للداخل"],
    safety: ["تمرن قرب حائط للاستناد"],
    breathing: "شهيق نزولاً · زفير صعوداً",
    progression: ["goblet-squat", "pistol-squat"],
    alternatives: ["bodyweight-squat"],
    reference: REF_NSCA,
  },
  {
    id: "lunge",
    name: "خطوة أمامية",
    latin: "Forward Lunge",
    category: "legs",
    level: "beginner",
    equipment: ["none"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "core"],
    location: ["home", "outdoor"],
    goals: ["general-fitness", "endurance"],
    contraindicated: ["knee"],
    pose: "squat",
    tempo: 3,
    caloriesPerMin: 7,
    recommendedSets: 3,
    recommendedReps: "10 لكل ساق",
    restSeconds: 45,
    cue: "الركبة الأمامية فوق الكاحل، الجذع مستقيم",
    mistakes: ["الركبة تتقدم أصابع القدم بشدة", "ميل الجذع"],
    safety: ["ابدأ بخطوات قصيرة"],
    breathing: "شهيق نزولاً · زفير صعوداً",
    progression: ["lunge", "walking-lunge", "reverse-lunge"],
    alternatives: ["bodyweight-squat"],
    reference: REF_NASM,
  },
  {
    id: "reverse-lunge",
    name: "خطوة خلفية",
    latin: "Reverse Lunge",
    category: "legs",
    level: "beginner",
    equipment: ["none"],
    primary: ["glutes"],
    secondary: ["quads", "hamstrings"],
    location: ["home"],
    goals: ["general-fitness"],
    contraindicated: [],
    pose: "squat",
    tempo: 3,
    caloriesPerMin: 7,
    recommendedSets: 3,
    recommendedReps: "10 لكل ساق",
    restSeconds: 45,
    cue: "خطوة كبيرة للخلف، انزل حتى تلمس الركبة الخلفية الأرض تقريباً",
    mistakes: ["تقدم الجذع", "قصر الخطوة"],
    safety: ["ألطف على الركبة من الأمامية"],
    breathing: "شهيق نزولاً · زفير صعوداً",
    progression: ["reverse-lunge", "lunge", "walking-lunge"],
    alternatives: ["bodyweight-squat"],
    reference: REF_NASM,
  },
  {
    id: "wall-sit",
    name: "الجلوس على الحائط",
    latin: "Wall Sit",
    category: "legs",
    level: "beginner",
    equipment: ["none"],
    primary: ["quads"],
    secondary: ["glutes", "core"],
    location: ["home"],
    goals: ["endurance"],
    contraindicated: ["knee"],
    pose: "squat",
    tempo: 5,
    caloriesPerMin: 5,
    recommendedSets: 3,
    recommendedReps: "30-60 ثانية",
    restSeconds: 45,
    cue: "الفخذان موازيان للأرض، الظهر ملتصق بالحائط",
    mistakes: ["ركبتان أعلى من 90°", "رفع الكعبين"],
    safety: ["توقف عند إحساس بحرقة شديدة في الركبة"],
    breathing: "تنفس منتظم ثابت",
    progression: ["wall-sit", "bodyweight-squat"],
    alternatives: ["bodyweight-squat"],
    reference: REF_ACSM,
  },
  {
    id: "glute-bridge",
    name: "جسر المؤخرة",
    latin: "Glute Bridge",
    category: "legs",
    level: "beginner",
    equipment: ["mat"],
    primary: ["glutes"],
    secondary: ["hamstrings", "core"],
    location: ["home"],
    goals: ["general-fitness", "mobility"],
    contraindicated: [],
    pose: "default",
    tempo: 3,
    caloriesPerMin: 5,
    recommendedSets: 3,
    recommendedReps: "12-15",
    restSeconds: 45,
    cue: "ادفع الوركين للأعلى واضغط عضلات المؤخرة في القمة",
    mistakes: ["تقوس أسفل الظهر", "دفع بالكعبين والأمشاط بلا توازن"],
    safety: ["مفيد بعد إصابات أسفل الظهر"],
    breathing: "زفير صعوداً · شهيق نزولاً",
    progression: ["glute-bridge", "single-leg-bridge", "hip-thrust"],
    alternatives: ["bodyweight-squat"],
    reference: REF_MCGILL,
  },

  // ============ CORE ============
  {
    id: "plank",
    name: "بلانك أمامي",
    latin: "Prone Forearm Plank",
    category: "core",
    level: "beginner",
    equipment: ["mat"],
    primary: ["core"],
    secondary: ["shoulders", "glutes"],
    location: ["home"],
    goals: ["general-fitness", "endurance"],
    contraindicated: ["shoulder"],
    pose: "plank",
    tempo: 4,
    caloriesPerMin: 5,
    recommendedSets: 3,
    recommendedReps: "30-60 ثانية",
    restSeconds: 45,
    cue: "شدّ البطن والمؤخرة، الوركان ثابتان، خط مستقيم من الرأس للكعب",
    mistakes: ["تدلي الحوض", "رفع المؤخرة", "الرأس معلق"],
    safety: ["أنهِ الجولة عند فقدان الاستقامة"],
    breathing: "تنفس بطني منتظم",
    progression: ["plank", "side-plank", "plank-shoulder-tap"],
    alternatives: ["knee-plank"],
    reference: REF_MCGILL,
  },
  {
    id: "side-plank",
    name: "بلانك جانبي",
    latin: "Side Plank",
    category: "core",
    level: "intermediate",
    equipment: ["mat"],
    primary: ["core"],
    secondary: ["shoulders", "glutes"],
    location: ["home"],
    goals: ["strength", "general-fitness"],
    contraindicated: ["shoulder"],
    pose: "plank",
    tempo: 4,
    caloriesPerMin: 6,
    recommendedSets: 3,
    recommendedReps: "30 ثانية لكل جهة",
    restSeconds: 45,
    cue: "الجسم بخط مستقيم، ارفع الورك عالياً",
    mistakes: ["الورك يهبط", "الرأس ينحرف"],
    safety: ["توقف عند ألم بالكتف"],
    breathing: "تنفس منتظم",
    progression: ["plank", "side-plank", "side-plank-hip-lift"],
    alternatives: ["plank"],
    reference: REF_MCGILL,
  },
  {
    id: "dead-bug",
    name: "الخنفساء الميتة",
    latin: "Dead Bug",
    category: "core",
    level: "beginner",
    equipment: ["mat"],
    primary: ["core"],
    secondary: [],
    location: ["home"],
    goals: ["general-fitness", "mobility"],
    contraindicated: [],
    pose: "default",
    tempo: 4,
    caloriesPerMin: 4,
    recommendedSets: 3,
    recommendedReps: "10 لكل جهة",
    restSeconds: 30,
    cue: "أسفل ظهرك ملتصق بالأرض، ذراع وساق معاكسة تتحركان ببطء",
    mistakes: ["تقوس أسفل الظهر", "التسرع"],
    safety: ["ممتاز لآلام أسفل الظهر"],
    breathing: "زفير مع مد الأطراف",
    progression: ["dead-bug", "bird-dog"],
    alternatives: ["bird-dog"],
    reference: REF_MCGILL,
  },
  {
    id: "bird-dog",
    name: "الطائر الصياد",
    latin: "Bird Dog",
    category: "core",
    level: "beginner",
    equipment: ["mat"],
    primary: ["core"],
    secondary: ["back", "glutes"],
    location: ["home"],
    goals: ["general-fitness", "mobility"],
    contraindicated: [],
    pose: "default",
    tempo: 4,
    caloriesPerMin: 4,
    recommendedSets: 3,
    recommendedReps: "10 لكل جهة",
    restSeconds: 30,
    cue: "على أربع، مد ذراع وساق معاكسة مع ثبات الحوض",
    mistakes: ["دوران الحوض", "تقوس الظهر"],
    safety: ["حركة موصى بها للتأهيل"],
    breathing: "زفير مع المد",
    progression: ["dead-bug", "bird-dog"],
    alternatives: ["dead-bug"],
    reference: REF_MCGILL,
  },
  {
    id: "mountain-climber",
    name: "متسلق الجبل",
    latin: "Mountain Climber",
    category: "core",
    level: "intermediate",
    equipment: ["mat"],
    primary: ["core"],
    secondary: ["shoulders", "quads"],
    location: ["home", "outdoor"],
    goals: ["fat-loss", "endurance"],
    contraindicated: ["shoulder", "wrist"],
    pose: "plank",
    tempo: 1,
    caloriesPerMin: 11,
    recommendedSets: 3,
    recommendedReps: "30-45 ثانية",
    restSeconds: 45,
    cue: "بلانك عالٍ، بدّل الركبتين للصدر بسرعة مع ثبات الوركين",
    mistakes: ["رفع الوركين", "لمس الأرض بضعف"],
    safety: ["اخفض السرعة عند ألم بالرسغ"],
    breathing: "تنفس سريع منتظم",
    progression: ["mountain-climber", "burpee"],
    alternatives: ["high-knees"],
    reference: REF_ACSM,
  },

  // ============ CARDIO / HIIT ============
  {
    id: "burpee",
    name: "بيربي كاملة",
    latin: "Full Burpee",
    category: "cardio",
    level: "advanced",
    equipment: ["none"],
    primary: ["full-body"],
    secondary: ["core", "quads", "chest"],
    location: ["home", "outdoor"],
    goals: ["fat-loss", "endurance"],
    contraindicated: ["knee", "wrist", "shoulder"],
    pose: "burpee",
    tempo: 2.5,
    caloriesPerMin: 14,
    recommendedSets: 4,
    recommendedReps: "8-12",
    restSeconds: 60,
    cue: "قرفصاء → بلانك → ضغطة (اختياري) → قفزة قوية",
    mistakes: ["هبوط الوركين", "قفز غير متحكم"],
    safety: ["استبدل القفزة بخطوة عند إصابة"],
    breathing: "زفير مع القفزة",
    progression: ["mountain-climber", "burpee"],
    alternatives: ["mountain-climber"],
    reference: REF_ACSM,
  },
  {
    id: "high-knees",
    name: "ركض الركب العالية",
    latin: "High Knees",
    category: "cardio",
    level: "beginner",
    equipment: ["none"],
    primary: ["quads"],
    secondary: ["calves", "core"],
    location: ["home", "outdoor"],
    goals: ["fat-loss", "endurance"],
    contraindicated: ["knee"],
    pose: "warmup",
    tempo: 1,
    caloriesPerMin: 12,
    recommendedSets: 3,
    recommendedReps: "30-45 ثانية",
    restSeconds: 30,
    cue: "ارفع الركبتين حتى مستوى الحوض بسرعة عالية",
    mistakes: ["الجذع منحنٍ للخلف", "هبوط ثقيل"],
    safety: ["اهبط على مقدمة القدم"],
    breathing: "تنفس منتظم سريع",
    progression: ["high-knees", "mountain-climber", "burpee"],
    alternatives: ["mountain-climber"],
    reference: REF_ACSM,
  },
  {
    id: "jumping-jack",
    name: "قفزة النجمة",
    latin: "Jumping Jack",
    category: "cardio",
    level: "beginner",
    equipment: ["none"],
    primary: ["full-body"],
    secondary: ["calves", "shoulders"],
    location: ["home", "outdoor"],
    goals: ["fat-loss", "endurance"],
    contraindicated: ["knee", "ankle"],
    pose: "warmup",
    tempo: 1,
    caloriesPerMin: 10,
    recommendedSets: 3,
    recommendedReps: "30-60 ثانية",
    restSeconds: 30,
    cue: "ذراعان لأعلى وقدمان جانبيتان معاً في تناغم",
    mistakes: ["هبوط بركب متيبسة"],
    safety: ["استبدل بـstep-jack عند إصابة الركبة"],
    breathing: "تنفس منتظم",
    progression: ["jumping-jack", "high-knees"],
    alternatives: ["high-knees"],
    reference: REF_WHO,
  },

  // ============ WARMUP / COOLDOWN / MOBILITY ============
  {
    id: "dynamic-warmup",
    name: "إحماء ديناميكي",
    latin: "Dynamic Warm-up (RAMP)",
    category: "warmup",
    level: "beginner",
    equipment: ["none"],
    primary: ["full-body"],
    secondary: [],
    location: ["home", "gym", "outdoor"],
    goals: ["general-fitness", "mobility"],
    contraindicated: [],
    pose: "warmup",
    tempo: 1.4,
    caloriesPerMin: 5,
    recommendedSets: 1,
    recommendedReps: "5-8 دقائق",
    restSeconds: 0,
    cue: "ارفع النبض تدريجياً بحركات مركّبة (بروتوكول RAMP)",
    mistakes: ["تمدد استاتيكي بارد", "شدة عالية مبكرة"],
    safety: ["ابدأ ببطء وارفع الشدة تدريجياً"],
    breathing: "تنفس عميق",
    progression: ["dynamic-warmup"],
    alternatives: [],
    reference: "Jeffreys I. (2006) — Warm-up revisited: the RAMP method.",
  },
  {
    id: "cat-cow",
    name: "القط - البقرة",
    latin: "Cat-Cow Stretch",
    category: "mobility",
    level: "beginner",
    equipment: ["mat"],
    primary: ["back"],
    secondary: ["core"],
    location: ["home"],
    goals: ["mobility"],
    contraindicated: [],
    pose: "cooldown",
    tempo: 4,
    caloriesPerMin: 3,
    recommendedSets: 2,
    recommendedReps: "10 دورات",
    restSeconds: 15,
    cue: "على أربع، تبادل تقويس وتقعير العمود ببطء",
    mistakes: ["حركة سريعة", "شد الرقبة"],
    safety: ["ممتاز لبداية اليوم"],
    breathing: "شهيق مع التقعير · زفير مع التقويس",
    progression: ["cat-cow"],
    alternatives: ["child-pose"],
    reference: REF_MCGILL,
  },
  {
    id: "child-pose",
    name: "وضعية الطفل",
    latin: "Child's Pose",
    category: "cooldown",
    level: "beginner",
    equipment: ["mat"],
    primary: ["back"],
    secondary: [],
    location: ["home"],
    goals: ["mobility"],
    contraindicated: [],
    pose: "cooldown",
    tempo: 5,
    caloriesPerMin: 2,
    recommendedSets: 1,
    recommendedReps: "60-90 ثانية",
    restSeconds: 0,
    cue: "الجلوس على الكعبين، الذراعان ممدودتان أماماً، الجبهة تلامس الأرض",
    mistakes: ["شد الرقبة", "رفع المؤخرة"],
    safety: ["يمكن وضع وسادة تحت البطن للحوامل"],
    breathing: "تنفس بطني بطيء",
    progression: ["child-pose"],
    alternatives: ["cat-cow"],
    reference: REF_ACSM,
  },
  {
    id: "static-cooldown",
    name: "تمدد ختامي شامل",
    latin: "Static Cool-Down Stretch",
    category: "cooldown",
    level: "beginner",
    equipment: ["mat"],
    primary: ["full-body"],
    secondary: [],
    location: ["home", "gym"],
    goals: ["mobility"],
    contraindicated: [],
    pose: "cooldown",
    tempo: 5,
    caloriesPerMin: 3,
    recommendedSets: 1,
    recommendedReps: "5-10 دقائق",
    restSeconds: 0,
    cue: "ثبّت كل وضعية 20-30 ثانية دون ارتداد",
    mistakes: ["ارتداد", "حبس النفس"],
    safety: ["توقف عند أي ألم حاد"],
    breathing: "تنفس عميق من الأنف",
    progression: ["static-cooldown"],
    alternatives: [],
    reference: "ACSM Position Stand — Garber et al. (2011).",
  },
  {
    id: "hip-opener",
    name: "فتح مفصل الحوض",
    latin: "90/90 Hip Opener",
    category: "mobility",
    level: "beginner",
    equipment: ["mat"],
    primary: ["hips" as unknown as Muscle],
    secondary: ["glutes"],
    location: ["home"],
    goals: ["mobility"],
    contraindicated: [],
    pose: "cooldown",
    tempo: 4,
    caloriesPerMin: 3,
    recommendedSets: 2,
    recommendedReps: "8 دورات لكل جهة",
    restSeconds: 15,
    cue: "الساقان بزاوية 90/90، بدّل الجهات ببطء بتحكم",
    mistakes: ["الاندفاع بالوركين", "تقوس الظهر"],
    safety: ["مفيد للجالسين طويلاً"],
    breathing: "تنفس منتظم",
    progression: ["hip-opener"],
    alternatives: ["cat-cow"],
    reference: REF_NASM,
  },
];

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function progressionLadder(id: string): Exercise[] {
  const ex = getExercise(id);
  if (!ex) return [];
  return ex.progression
    .map((pid) => getExercise(pid))
    .filter((e): e is Exercise => Boolean(e));
}
